# Streamlit secrets for PixelPulse AI
OPENAI_API_KEY="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"
